export const state = {
    mainColor: "#9C1820",
    routeGetDirectory: `${window.location["origin"]}/media-api/index`,
    routeGetMedia: `${window.location["origin"]}/media-api/show/`,
    routeCreateDirectory: `${window.location["origin"]}/media-api/directory/create`,
    routeDeleteDirectory: `${window.location["origin"]}/media-api/directory/destroy`,
    routeDeleteMedia: `${window.location["origin"]}/media-api/destroy`,
    routeMoveDirectory: `${window.location["origin"]}/media-api/directory/update`,
    routeSearchMedia: `${window.location["origin"]}/media-api/search`,
    routeUpdateMedia: `${window.location["origin"]}/media-api/update`,
    hideDirectory: false,
    currentDirectory: null,
    selectedDirectory: null,
    selectedTranslation: null,
    totalSelected: 0,
    modalState: {
        add: false,
        create: false,
        delete: false,
        move: false
    },
    folderState: true,
    viewState: false,
    selectedElem: [],
    directoryCollection: [],
    moveDirectoryCollection: [],
    mediaCollection: [],
    mediaTypeArray: [],
    orderBy: "created_at",
    orderDirection: "asc",
    isLoading: true,
    isLoadingSidePanel: false,
    isSearch: false,
    haveContextMenu: false,
    lang: 'en',
    pageCount: null,
    allMediaLoaded: false
};
