<?php

namespace Plank\MediaManager\Tests;

use Illuminate\Support\Facades\DB;
use Orchestra\Testbench\TestCase as TestBench;
use Plank\Mediable\MediableServiceProvider;
use Plank\MediaManager\MediaManagerServiceProvider;
use Plank\MediaManager\Models\Media;

class TestCase extends TestBench
{
    protected $loadEnvironmentVariables = true;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app)
    {
        return [MediableServiceProvider::class, MediaManagerServiceProvider::class];
    }

    protected function defineDatabaseMigrations()
    {
        $this->loadMigrationsFrom(__DIR__."/../vendor/plank/laravel-mediable/migrations");
        $this->loadMigrationsFrom(__DIR__."/database");
    }

//    protected function getEnvironmentSetUp($app)
//    {
//        if (!file_exists(__DIR__."/../.env")) {
//            copy(__DIR__."/../.env.testing", __DIR__."/../.env");
//        }
//    }

    public function ignorePackageDiscoveriesFrom()
    {
        return [];
    }
}
